export const TEAM_DATA = {
  core: [
    {
      id: 1,
      name: "Junaid Tarafdar",
      role: "President",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732945/core_team_2025/junaid_tarafdar.webp",
      instagram: "https://www.instagram.com/_.tfzuu._/",
      linkedin: "",
    },
    {
      id: 2,
      name: "Ashutosh Roy",
      role: "Vice President",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732948/core_team_2025/ashutosh_roy.webp",
      instagram: "https://www.instagram.com/damnitsroy/",
      linkedin: "#",
    },
    {
      id: 3,
      name: "Sayan Khan",
      role: "General Secretary",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732950/core_team_2025/sayan_khan.webp",
      instagram: "https://www.instagram.com/sayank2004/",
      linkedin: "#",
    },
    {
      id: 4,
      name: "Krishnava Ghosh",
      role: "Tech Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732951/core_team_2025/krishnava_ghosh.webp",
      instagram: "https://www.instagram.com/krishnava_ghosh/",
      linkedin: "#",
    },
    {
      id: 5,
      name: "Rhishav Chanda",
      role: "Sponsorship Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732952/core_team_2025/rhishav_chanda.webp",
      instagram: "https://www.instagram.com/rhishavvv/",
      linkedin: "#",
    },
    {
      id: 6,
      name: "Mrittika Majumder",
      role: "Treasurer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732954/core_team_2025/mrittika_majumder.webp",
      instagram: "https://www.instagram.com/mri.tt.ika/",
      linkedin: "#",
    },
    {
      id: 7,
      name: "Sibanjali Singh",
      role: "PR and Marketing Head",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,c_limit,w_auto/v1767083203/core_team_2025/shi_elczkz.jpg",
      instagram: "#",
      linkedin: "#",
    },
    {
      id: 8,
      name: "Sayan Majumder",
      role: "Content and Creative Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732957/core_team_2025/sayan_majumder.webp",
      instagram: "https://www.instagram.com/meghdutam_8/",
      linkedin: "#",
    },
    {
      id: 9,
      name: "Swarnadeep Dawn",
      role: "Operation Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732959/core_team_2025/swarnadeep_dawn.webp",
      instagram: "#",
      linkedin: "#",
    },
    {
      id: 10,
      name: "Tuhin Ghosh",
      role: "Logistics Head",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732961/core_team_2025/tuhin_ghosh.webp",
      instagram: "https://www.instagram.com/_verses_in_blue_/",
      linkedin: "#",
    },
    {
      id: 11,
      name: "Asmita Chatterjee",
      role: "Sponsorship Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/v1760732963/core_team_2025/asmita_chatterjee.webp",
      instagram: "https://www.instagram.com/asmita.tina/",
      linkedin: "#",
    },
    {
      id: 12,
      name: "Srestha Aich",
      role: "PR & Marketing Head",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,c_limit,w_auto/v1767082644/core_team_2025/Sibanjali_Singh_nimjkz.jpg",
      instagram: "https://www.instagram.com/sresthaaaaa_04/",
      linkedin: "#",
    },
  ],



  wings: [
    {
      id: 1,
      name: "Sukalyan Roy",
      role: "Cybernix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958339/Wing/xvs6asbbvel42clmsith.jpg",
      instagram: "https://www.instagram.com/adverb_adjective?igsh=ZWp5c3FvZnB1dzFh",
      linkedin: "#",
    },
    {
      id: 2,
      name: "Sebanti Dasgupta",
      role: "Cybernix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958198/Wing/rltocgasaik2i7po1rgg.jpg",
      instagram: "https://www.instagram.com/sdasgupta39?igsh=ZDZ6eWNpNjEwMDNn",
      linkedin: "#",
    },
    {
      id: 3,
      name: "Anusuya Pan",
      role: "Illustro Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958445/Wing/odd1vobr4svdx4is5bt1.jpg",
      instagram: "https://www.instagram.com/misssbrightsidee?igsh=Z2t1b2h6cHdlZzZ2",
      linkedin: "#",
    },
    {
      id: 4,
      name: "Tania Choudhury",
      role: "Illustro Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958450/Wing/yur5ck0te1ajmvdcnd7q.jpg",
      instagram: "https://www.instagram.com/a_i_n_a_t?igsh=dXpnaTAzcDk1YXFx",
      linkedin: "#",
    },
    {
      id: 5,
      name: "Anushka Tarafdar",
      role: "Robonix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958383/Wing/idsmkfxajz7qmevedwhi.jpg",
      instagram: "https://www.instagram.com/anushka_tarafdar?igsh=cXl3eDV5Z2doMWlt",
      linkedin: "#",
    },
    {
      id: 6,
      name: "Soumyarup Chakraborty",
      role: "Robonix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958388/Wing/brlqiumipbhe3bml5ame.jpg",
      instagram: "https://www.instagram.com/soumyarup_chakraborty?igsh=YmxnMnBpdTBvdG40",
      linkedin: "#",
    },
    {
      id: 7,
      name: "Ritam Bhattacharya",
      role: "Eloquense Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958204/Wing/gd39x5jm867dkwmwqfaa.jpg",
      instagram: "https://www.instagram.com/ritam.333?igsh=bjVua2hld3lwa2Fi",
      linkedin: "#",
    },
    {
      id: 8,
      name: "Arpan Biswas",
      role: "Eloquense Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958211/Wing/liqbu7oi94rs3ayz62tu.jpg",
      instagram: "#",
      linkedin: "#",
    },
    {
      id: 9,
      name: "Himaghna Ghosh",
      role: "Virtuix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958273/Wing/ko47rdigggxktx2rmmmj.jpg",
      instagram: "https://www.instagram.com/himaghna_ghosh_official?igsh=dHhnd2EweHdhODZ2",
      linkedin: "#",
    },
    {
      id: 10,
      name: "Debjit",
      role: "Virtuix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958313/Wing/fvkcnt05llzmpzm75lwm.jpg",
      instagram: "#",
      linkedin: "#",
    },
    {
      id: 11,
      name: "Arya Poddar",
      role: "Virtuix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958329/Wing/grjavreqj76pe7wnyngt.jpg",
      instagram: "#",
      linkedin: "#",
    },
    {
      id: 12,
      name: "Souharda Banerjee",
      role: "Virtuix Lead",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958335/Wing/fcfq8xiqjmez9oyplqen.jpg",
      instagram: "#",
      linkedin: "#",
    },
  ],

  dev: [
    {
      id: 1,
      name: "Krishnava Ghosh",
      role: "Web Administrator",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730676/web_team_2025/%E2%80%9Ckrishnava_ghosh_%22.jpg",
      instagram: "https://www.instagram.com/krishnava_ghosh/",
      linkedin: "https://www.linkedin.com/in/krishnavaghosh/",
    },
    {
      id: 2,
      name: "Sukalyan Roy",
      role: "Web Administrator",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_auto/v1760958339/Wing/xvs6asbbvel42clmsith.jpg",
      instagram: "https://www.instagram.com/adverb_adjective?igsh=ZWp5c3FvZnB1dzFh",
      linkedin: "https://www.linkedin.com/in/sukalyan-roy-457040362/",
    },
    {
      id: 3,
      name: "Sebanti Dasgupta",
      role: "Web Administrator",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730684/web_team_2025/%E2%80%9Csebanti_dasgupta%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/sdasgupta39/",
      linkedin: "https://www.linkedin.com/in/sebanti-dasgupta-515541243/",
    },
    {
      id: 4,
      name: "Anindita Dey",
      role: "FullStack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730685/web_team_2025/%E2%80%9Canindita_dey%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/__pastel_hues__/",
      linkedin: "https://www.linkedin.com/in/anindita-dey-b81210217/",
    },
    {
      id: 5,
      name: "Gourab Das",
      role: "FullStack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730687/web_team_2025/%E2%80%9Cgourab_das%E2%80%9C.jpg",
      instagram: "https://www.instagram.com/mrdot_it/",
      linkedin: "https://www.linkedin.com/in/gourab2005/",
    },
    {
      id: 6,
      name: "Sagnik Sarkar",
      role: "Full Stack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_600/v1768857211/web_team_2025/sagnik_ygxnbr.jpg",
      instagram: "https://www.instagram.com/sagnik2546/",
      linkedin: "https://www.linkedin.com/in/sagnik-sarkar095/",
    },
    {
      id: 7,
      name: "Nilardri Pramanick",
      role: "Full Stack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730692/web_team_2025/%E2%80%9Cnilardri_pramanick%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/___n_i_l_a_r_d_r_i___/",
      linkedin: "http://www.linkedin.com/in/nilardri-pramanick-3a6a15324/",
    },
    {
      id: 8,
      name: "Supriti Mishra",
      role: "Frontend Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730698/web_team_2025/%E2%80%9Csupriti_mishra%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/_https.supriti_?igsh=c3U3ZmY4bDhzZGI4",
      linkedin: "https://www.linkedin.com/in/supriti-mishra-6501b5313/",
    },
    {
      id: 9,
      name: "Ankit Talukder",
      role: "Full Stack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730701/web_team_2025/%E2%80%9Cankit_talukder%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/sadubaba_2061/",
      linkedin: "https://www.linkedin.com/in/ankit-talukder-631a62220/",
    },
        {
      id: 10,
      name: "DEBPRIYO GHOSAL",
      role: "Full Stack Developer",
      image: "https://res.cloudinary.com/dlbiliyzy/image/upload/f_auto,q_auto,w_800/v1760730690/web_team_2025/%E2%80%9Cdebpriyo_ghosal%E2%80%9D.jpg",
      instagram: "https://www.instagram.com/debpriyo.exe?igsh=dHB6NW1ncndzb2J0",
      linkedin: "https://www.linkedin.com/in/debpriyo-ghosal-0759a92a6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
  ],
};